### ISSUE TITLE
Benutzer löschen

### ISSUE THREAD

**Issue by loubi72** [Jubi72/archevp_bot#1]
@Zwelf Wir müssen es möglich machen, dass der Benutzer sich wirklich aus unserer Datenbank austragen kann, schon aus Datenschutzgründen. Das Gerüst ist schon im Bot gespeichert (Commit folgt nach dieser Nachricht).

**Comment by Zwelf** [comment]
Fixed by 116d85953dfd0c3d398d71b6a1448bdd1e0eb8e9
